### ISSUE TITLE
Failing Test

### ISSUE THREAD

**Issue by iswanj** [asbjornenge/react-datalist#16]
```
Error: Cannot find module 'react'
    at Function.Module._resolveFilename (module.js:325:15)
    at Function.Module._load (module.js:276:25)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/home/mariswan/works/opensource/react-datalist/test/spec.js:4:21)
    at Module._compile (module.js:409:26)
    at normalLoader (/home/mariswan/works/opensource/react-datalist/node_modules/babel-core/lib/api/register/node.js:199:5)
    at Object.require.extensions.(anonymous function) [as .js] (/home/mariswan/works/opensource/react-datalist/node_modules/babel-core/lib/api/register/node.js:216:7)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at /home/mariswan/works/opensource/react-datalist/node_modules/mocha/lib/mocha.js:184:27
    at Array.forEach (native)
    at Mocha.loadFiles (/home/mariswan/works/opensource/react-datalist/node_modules/mocha/lib/mocha.js:181:14)
    at Mocha.run (/home/mariswan/works/opensource/react-datalist/node_modules/mocha/lib/mocha.js:393:31)
    at loadAndRun (/home/mariswan/works/opensource/react-datalist/node_modules/mocha/bin/_mocha:335:22)
    at Object.<anonymous> (/home/mariswan/works/opensource/react-datalist/node_modules/mocha/bin/_mocha:352:3)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Function.Module.runMain (module.js:441:10)
    at startup (node.js:139:18)
    at node.js:968:3
```

**Comment by asbjornenge** [comment]
@iswanj probably a missing `npm install` ? :stuck_out_tongue:
